// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhYqPqSJLTWCKgSbL4x095K0SF9KVURFo',
    appId: '1:275869724018:android:730826458d01b87ea8c1eb',
    messagingSenderId: '275869724018',
    projectId: 'flutter-chat-app-f6743',
    storageBucket: 'flutter-chat-app-f6743.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWAsOw3mqrgWXuSEcoQtaLABj35hQrZPc',
    appId: '1:275869724018:ios:a17c309fb0e0d1b5a8c1eb',
    messagingSenderId: '275869724018',
    projectId: 'flutter-chat-app-f6743',
    storageBucket: 'flutter-chat-app-f6743.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjtfKXhnPzwiHzsdbti3TxuksR_jASZDw',
    appId: '1:275869724018:web:db7deba1650935c0a8c1eb',
    messagingSenderId: '275869724018',
    projectId: 'flutter-chat-app-f6743',
    authDomain: 'flutter-chat-app-f6743.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f6743.appspot.com',
  );

}